### ISSUE TITLE
Request to open meteo exception not caught

### ISSUE THREAD

**Issue by sjefferson99** [sjefferson99/pico-shed#51]
If the wifi connection is good, but the request cannot be made for any reason, such as no internet beyond the AP, exception OS error -2 is not caught and the fan stays off.

Exception should be handled gracefully and fan left on if no up to date humidity information is available.

**Comment by sjefferson99** [comment]
I only saw this briefly, it might be unrelated. I can see that the current request simply hangs waiting on a response if the wifi network is up but there is no route to open meteo. This needs handling, ideally async, but at least fail gracefully after short timeout.

**Comment by sjefferson99** [comment]
This relates to the non async function no longer in use. Async function yet to be tested for this error.

**Comment by sjefferson99** [comment]
With firewall blocking packets async code allows other execution to continue but request times out after around 30 seconds with:
Task exception wasn't retrieved
future: <Task> coro= <generator object 'assess_fan_state' at 20020f80>
Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run_until_complete
  File "lib/fan.py", line 105, in assess_fan_state
  File "lib/open_meteo.py", line 29, in get_humidity_async
  File "/lib/uaiohttpclient.py", line 77, in request
  File "asyncio/stream.py", line 1, in readline
OSError: [Errno 103] ECONNABORTED

Need to catch this error, set the fan state to on as if network failed to connect and if necessary restart the coroutine to assess fan state.
